name: Build and Publish image
on:
  [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: docker build . -t c0r0nel/flask-api-app:latest
      - name: Push image to docker hub
        run: |
          docker login -u c0r0nel -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push c0r0nel/flask-api-app:latest
